personajes = [
     {
        "_id": "5a12260f0f5ae10021650d75",
        "name": "Padma Patil",
        "role": "student",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1226520f5ae10021650d76",
        "name": "Parvati Patil",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "boggart": "mummy",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1226d70f5ae10021650d77",
        "name": "Peter Pettigrew",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Wormtail",
        "wand": "Chestnut, 9 1/4, dragon heartstring",
        "boggart": "Lord Voldemort",
        "animagus": "rat",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12273f0f5ae10021650d78",
        "name": "Antioch Peverell",
        "wand": "Elder, 15\", Thestral tail hair core",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a12276b0f5ae10021650d79",
        "name": "Cadmus Peverell",
        "role": "Owner of the resurrection stone",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a12279f0f5ae10021650d7a",
        "name": "Ignotus Peverell",
        "role": "Owner of the invisibility cloak",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1227e10f5ae10021650d7b",
        "name": "Irma Pince",
        "role": "Librarian, Hogwarts",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "boggart": "Lord Voldemort",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1228070f5ae10021650d7c",
        "name": "Sturgis Podmore",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1228930f5ae10021650d7d",
        "name": "Poppy Pomfrey",
        "role": "Matron, Hogwarts Hospital Wing",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12292a0f5ae10021650d7e",
        "name": "Harry Potter",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "The Boy Who Lived",
        "wand": "Holly, 11\", phoenix feather",
        "boggart": "dementor",
        "patronus": "stag",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a12298d0f5ae10021650d7f",
        "name": "James Potter I",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Prongs",
        "wand": "Mahogany, 11\", unknown core",
        "patronus": "stag",
        "animagus": "stag",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1229e10f5ae10021650d80",
        "name": "Lily J. Potter",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "wand": "Willow, 10 1/4\", unknown core",
        "patronus": "doe",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle-born",
        "species": "human"
    }, {
        "_id": "5a122a0e0f5ae10021650d81",
        "name": "Ernest Prang",
        "role": "Driver of the Knight Bus",
        "alias": "Ernie",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122a880f5ae10021650d82",
        "name": "Quirinus Quirrell",
        "role": "Professor, Defence Against the Dark Arts",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "wand": "Alder, 9\", unicorn hair",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a122ac40f5ae10021650d83",
        "name": "Helena Ravenclaw",
        "role": "Ravenclaw House Ghost",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Grey Lady",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "ghost"
    }, {
        "_id": "5a122aef0f5ae10021650d84",
        "name": "Rowena Ravenclaw",
        "role": "Founder, Hogwarts",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122b320f5ae10021650d85",
        "name": "Mary Riddle",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle",
        "species": "human"
    }, {
        "_id": "5a122b510f5ae10021650d86",
        "name": "Thomas Riddle",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle",
        "species": "human"
    }, {
        "_id": "5a122b930f5ae10021650d87",
        "name": "Tom Riddle Sr",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle",
        "species": "human"
    }, {
        "_id": "5a122c200f5ae10021650d88",
        "name": "Tom Riddle",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Lord Voldemort",
        "wand": "Yew, 13 1/2\", phoenix feather core",
        "boggart": "his own corpse",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a122cbe0f5ae10021650d89",
        "name": "Demelza Robins",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122cf40f5ae10021650d8a",
        "name": "Augustus Rockwood",
        "role": "Unspeakable",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122ea30f5ae10021650d8b",
        "name": "Albert Runcorn",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a122ecc0f5ae10021650d8c",
        "name": "Scabior",
        "role": "Snatcher",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122f3d0f5ae10021650d8d",
        "name": "Newton Scamander ",
        "role": "Author, Fantastic Beasts and Where to Find Them",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Newt ",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122f750f5ae10021650d8e",
        "name": "Rufus Scrimgeour",
        "role": "Head of Auror Office",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a122fc60f5ae10021650d8f",
        "name": "Kingsley Shacklebolt",
        "role": "Auror",
        "patronus": "lynx",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1230070f5ae10021650d90",
        "name": "Stanley Shunpike",
        "role": "Conductor of the Knight Bus",
        "alias": "Stan ",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1230e90f5ae10021650d91",
        "name": "Aurora Sinistra",
        "role": "Professor, Astronomy",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1231fd0f5ae10021650d92",
        "name": "Rita Skeeter",
        "role": "Gossip Correspondant for the Daily Prophet",
        "alias": "Queen of the Quills",
        "animagus": "beetle",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1232600f5ae10021650d93",
        "name": "Horace Slughorn",
        "role": "Professor, Potions",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "wand": "Cedar, 10 1/4\", dragon heartstring",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12327c0f5ae10021650d94",
        "name": "Salazar Slytherin",
        "role": "Founder, Hogwarts",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1232b10f5ae10021650d95",
        "name": "Hepzibah Smith",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12333f0f5ae10021650d96",
        "name": "Zacharias Smith",
        "role": "student",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1233bc0f5ae10021650d97",
        "name": "Severus Snape",
        "role": "Professor, Potions",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "patronus": "doe",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a1233ff0f5ae10021650d98",
        "name": "Alicia Spinnet",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1234500f5ae10021650d99",
        "name": "Pomona Sprout",
        "role": "Professor, Herbology",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1234820f5ae10021650d9a",
        "name": "Pius Thicknesse",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1234cb0f5ae10021650d9b",
        "name": "Dean Thomas",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "boggart": "severed hand walking on it's own",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a1235060f5ae10021650d9c",
        "name": "Andromeda Tonks",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1235790f5ae10021650d9d",
        "name": "Nymphadora Tonks",
        "role": "Auror",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Tonks",
        "patronus": "wolf",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human (metamorphmagus)"
    }, {
        "_id": "5a1235c10f5ae10021650d9e",
        "name": "Edward Tonks",
        "alias": "Ted",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle-born",
        "species": "human"
    }, {
        "_id": "5a12361f0f5ae10021650d9f",
        "name": "Travers",
        "role": "Ministry of Magic Official",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12368a0f5ae10021650da0",
        "name": "Sybill Trelawney",
        "role": "Professor, Divination",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "wand": "Hazel, 9 1/2\", unicorn hair",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a1236eb0f5ae10021650da1",
        "name": "Dolores Umbridge",
        "role": "Head of the Muggle Born Registration Commission",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "wand": "Birch, 8\", dragon heartstring",
        "patronus": "persian cat",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "half-blood",
        "species": "human"
    }, {
        "_id": "5a1237150f5ae10021650da2",
        "name": "Emmeline Vance",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1237480f5ae10021650da3",
        "name": "Romilda Vane",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a12376d0f5ae10021650da4",
        "name": "Septima Vector",
        "role": "Professor, Arithmancy",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a1237c00f5ae10021650da5",
        "name": "Arthur Weasley",
        "role": "Head, Misuse of Muggle Artifacts ",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "patronus": "weasel",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1238070f5ae10021650da6",
        "name": "William Weasley",
        "role": "Curse Breaker, Gringotts Bank",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Bill",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1238350f5ae10021650da7",
        "name": "Charles Weasley",
        "role": "Dragonologist",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Charlie",
        "wand": "Ash, 12\", unicorn hair tail",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a12387a0f5ae10021650da8",
        "name": "Fred Weasley",
        "role": "co-owner of Weasleys' Wizard Wheezes",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1238b20f5ae10021650da9",
        "name": "George Weasley",
        "role": "co-owner of Weasleys' Wizard Wheezes",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1239130f5ae10021650daa",
        "name": "Ginevra Weasley",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Ginny",
        "patronus": "horse",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a12393d0f5ae10021650dab",
        "name": "Molly Weasley",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "boggart": "corpses of her family",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a12395f0f5ae10021650dac",
        "name": "Percy Weasley",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1239c80f5ae10021650dad",
        "name": "Ronald Weasley",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Ron",
        "wand": "Willow, 14\", unicorn hair tail",
        "boggart": "Aragog",
        "patronus": "jack russell terrier",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": true,
        "dumbledoresArmy": true,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a1239f10f5ae10021650dae",
        "name": "Oliver Wood",
        "role": "student",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123a110f5ae10021650daf",
        "name": "Kennilworthy Whisp",
        "role": "Author, Quiddich Through The Ages",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123a460f5ae10021650db0",
        "name": "Corban Yaxley",
        "__v": 0,
        "ministryOfMagic": true,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": true,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123a710f5ae10021650db1",
        "name": "Blaise Zabini",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123a950f5ae10021650db2",
        "name": "Aragog",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "acromantula"
    }, {
        "_id": "5a123aa70f5ae10021650db3",
        "name": "Bane",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "centaur"
    }, {
        "_id": "5a123ac60f5ae10021650db4",
        "name": "Beedle the Bard",
        "role": "Fairytale Author",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123af40f5ae10021650db5",
        "name": "Bloody Baron",
        "role": "Slytherin House Ghost",
        "house": "Slytherin",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "ghost"
    }, {
        "_id": "5a123b110f5ae10021650db6",
        "name": "Buckbeak",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "hippogriff"
    }, {
        "_id": "5a123b450f5ae10021650db7",
        "name": "Cadogan",
        "role": "Gryffindor Tower Door Guard",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "pure-blood",
        "species": "human"
    }, {
        "_id": "5a123bfa0f5ae10021650db8",
        "name": "Crookshanks",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "cat"
    }, {
        "_id": "5a123c260f5ae10021650db9",
        "name": "Dobby",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "house-elf"
    }, {
        "_id": "5a123c710f5ae10021650dba",
        "name": "Errol",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "Great Grey Owl"
    }, {
        "_id": "5a123c8c0f5ae10021650dbb",
        "name": "Fang",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "Boarhound"
    }, {
        "_id": "5a123cb40f5ae10021650dbc",
        "name": "Fat Friar",
        "role": "Hufflepuff House Ghost",
        "house": "Hufflepuff",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "ghost"
    }, {
        "_id": "5a123cd20f5ae10021650dbd",
        "name": "Fridfwulfa",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "giant"
    }, {
        "_id": "5a123cf00f5ae10021650dbe",
        "name": "Fat Lady",
        "role": "Gryffindor Tower Door Guard",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "portrait"
    }, {
        "_id": "5a123d3a0f5ae10021650dbf",
        "name": "Fawkes",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "phoenix"
    }, {
        "_id": "5a123d520f5ae10021650dc0",
        "name": "Firenze",
        "role": "Professor, Divination",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "centaur"
    }, {
        "_id": "5a123d680f5ae10021650dc1",
        "name": "Fluffy",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "three-headed dog"
    }, {
        "_id": "5a123d7c0f5ae10021650dc2",
        "name": "Grawp",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "giant"
    }, {
        "_id": "5a123d9b0f5ae10021650dc3",
        "name": "Griphook",
        "role": "Employee, Gringotts Wizarding Bank",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "goblin"
    }, {
        "_id": "5a123db20f5ae10021650dc4",
        "name": "Hedwig",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "Snowy Owl"
    }, {
        "_id": "5a123dc30f5ae10021650dc5",
        "name": "Hokey",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "house-elf"
    }, {
        "_id": "5a123de10f5ae10021650dc6",
        "name": "Kreacher",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "house-elf"
    }, {
        "_id": "5a123df10f5ae10021650dc7",
        "name": "Magorian",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "centaur"
    }, {
        "_id": "5a123e450f5ae10021650dc8",
        "name": "Myrtle Warren",
        "role": "student",
        "house": "Ravenclaw",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Moaning Myrtle",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "muggle-born",
        "species": "ghost"
    }, {
        "_id": "5a123e600f5ae10021650dc9",
        "name": "Mrs. Norris",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "cat"
    }, {
        "_id": "5a123e870f5ae10021650dca",
        "name": "Great Aunt Muriel",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123e9f0f5ae10021650dcb",
        "name": "Nagini",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "horcrux"
    }, {
        "_id": "5a123f130f5ae10021650dcc",
        "name": "Nicholas de Mimsy-Porpington",
        "role": "Gryffindor House Ghost",
        "house": "Gryffindor",
        "school": "Hogwarts School of Witchcraft and Wizardry",
        "alias": "Nearly Headless Nick",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "ghost"
    }, {
        "_id": "5a123f3b0f5ae10021650dcd",
        "name": "Norbert",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "Norwegian Ridgeback"
    }, {
        "_id": "5a123f7c0f5ae10021650dce",
        "name": "Peeves",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "poltergeist"
    }, {
        "_id": "5a123f970f5ae10021650dcf",
        "name": "Pigwidgeon",
        "alias": "Pig",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "scops owl"
    }, {
        "_id": "5a123fbf0f5ae10021650dd0",
        "name": "Madam Rosmerta",
        "role": "Owner, The Three Broomsticks",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "human"
    }, {
        "_id": "5a123fd20f5ae10021650dd1",
        "name": "Ronan",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "centaur"
    }, {
        "_id": "5a123fe30f5ae10021650dd2",
        "name": "Trevor",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "toad"
    }, {
        "_id": "5a123fff0f5ae10021650dd3",
        "name": "Winky",
        "__v": 0,
        "ministryOfMagic": false,
        "orderOfThePhoenix": false,
        "dumbledoresArmy": false,
        "deathEater": false,
        "bloodStatus": "unknown",
        "species": "house-elf"
    }]

module.exports = personajes;