personajes = [
    {
    _id: '5a12260f0f5ae10021650d75',
    name: 'Padma Patil',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/padmaPatil.jpg'
  },
  {
    _id: '5a1226520f5ae10021650d76',
    name: 'Parvati Patil',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/parvatiPatil.jpg'
  },
  {
    _id: '5a1226d70f5ae10021650d77',
    name: 'Peter Pettigrew',
    role: undefined,
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/peterPettigrew.jpg'
  },
  {
    _id: '5a12273f0f5ae10021650d78',
    name: 'Antioch Peverell',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/antiochPeverell.jpg'
  },
  {
    _id: '5a12276b0f5ae10021650d79',
    name: 'Cadmus Peverell',
    role: 'Owner of the resurrection stone',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/cadmusPeverell.jpg'
  },
  {
    _id: '5a12279f0f5ae10021650d7a',
    name: 'Ignotus Peverell',
    role: 'Owner of the invisibility cloak',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/ignotusPeverell.jpg'
  },
  {
    _id: '5a1227e10f5ae10021650d7b',
    name: 'Irma Pince',
    role: 'Librarian, Hogwarts',
    house: undefined,
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/irmaPince.jpg'
  },
  {
    _id: '5a1228070f5ae10021650d7c',
    name: 'Sturgis Podmore',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/sturgisPodmore.jpg'
  },
  {
    _id: '5a1228930f5ae10021650d7d',
    name: 'Poppy Pomfrey',
    role: 'Matron, Hogwarts Hospital Wing',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/poppyPomfrey.jpg'
  },
  {
    _id: '5a12292a0f5ae10021650d7e',
    name: 'Harry Potter',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/harryPotter.jpg'
  },
  {
    _id: '5a12298d0f5ae10021650d7f',
    name: 'James Potter I',
    role: undefined,
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/jamesPotter.jpg'
  },
  {
    _id: '5a1229e10f5ae10021650d80',
    name: 'Lily J. Potter',
    role: undefined,
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
    image: './src/assets/img/lilyJ..jpg'
  },
  {
    _id: '5a122a0e0f5ae10021650d81',
    name: 'Ernest Prang',
    role: 'Driver of the Knight Bus',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/ernestPrang.jpg'
  },
  {
    _id: '5a122a880f5ae10021650d82',
    name: 'Quirinus Quirrell',
    role: 'Professor, Defence Against the Dark Arts',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/quirinusQuirrell.jpg'
  },
  {
    _id: '5a122ac40f5ae10021650d83',
    name: 'Helena Ravenclaw',
    role: 'Ravenclaw House Ghost',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
    image: './src/assets/img/helenaRavenclaw.jpg'
  },
  {
    _id: '5a122aef0f5ae10021650d84',
    name: 'Rowena Ravenclaw',
    role: 'Founder, Hogwarts',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/rowenaRavenclaw.jpg'
  },
  {
    _id: '5a122b320f5ae10021650d85',
    name: 'Mary Riddle',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
    image: './src/assets/img/maryRiddle.jpg'
  },
  {
    _id: '5a122b510f5ae10021650d86',
    name: 'Thomas Riddle',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
    image: './src/assets/img/thomasRiddle.jpg'
  },
  {
    _id: '5a122b930f5ae10021650d87',
    name: 'Tom Riddle Sr',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
    image: './src/assets/img/tomRiddle.jpg'
  },
  {
    _id: '5a122c200f5ae10021650d88',
    name: 'Tom Riddle',
    role: undefined,
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/tomRiddle.jpg'
  },
  {
    _id: '5a122cbe0f5ae10021650d89',
    name: 'Demelza Robins',
    role: undefined,
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/demelzaRobins.jpg'
  },
  {
    _id: '5a122cf40f5ae10021650d8a',
    name: 'Augustus Rockwood',
    role: 'Unspeakable',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/augustusRockwood.jpg'
  },
  {
    _id: '5a122ea30f5ae10021650d8b',
    name: 'Albert Runcorn',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/albertRuncorn.jpg'
  },
  {
    _id: '5a122ecc0f5ae10021650d8c',
    name: 'Scabior',
    role: 'Snatcher',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/scabior.jpg'
  },
  {
    _id: '5a122f3d0f5ae10021650d8d',
    name: 'Newton Scamander ',
    role: 'Author, Fantastic Beasts and Where to Find Them',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/newtonScamander.jpg'
  },
  {
    _id: '5a122f750f5ae10021650d8e',
    name: 'Rufus Scrimgeour',
    role: 'Head of Auror Office',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/rufusScrimgeour.jpg'
  },
  {
    _id: '5a122fc60f5ae10021650d8f',
    name: 'Kingsley Shacklebolt',
    role: 'Auror',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/kingsleyShacklebolt.jpg'
  },
  {
    _id: '5a1230070f5ae10021650d90',
    name: 'Stanley Shunpike',
    role: 'Conductor of the Knight Bus',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/stanleyShunpike.jpg'
  },
  {
    _id: '5a1230e90f5ae10021650d91',
    name: 'Aurora Sinistra',
    role: 'Professor, Astronomy',
    house: undefined,
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/auroraSinistra.jpg'
  },
  {
    _id: '5a1231fd0f5ae10021650d92',
    name: 'Rita Skeeter',
    role: 'Gossip Correspondant for the Daily Prophet',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/ritaSkeeter.jpg'
  },
  {
    _id: '5a1232600f5ae10021650d93',
    name: 'Horace Slughorn',
    role: 'Professor, Potions',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/horaceSlughorn.jpg'
  },
  {
    _id: '5a12327c0f5ae10021650d94',
    name: 'Salazar Slytherin',
    role: 'Founder, Hogwarts',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/salazarSlytherin.jpg'
  },
  {
    _id: '5a1232b10f5ae10021650d95',
    name: 'Hepzibah Smith',
    role: undefined,
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/hepzibahSmith.jpg'
  },
  {
    _id: '5a12333f0f5ae10021650d96',
    name: 'Zacharias Smith',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/zachariasSmith.jpg'
  },
  {
    _id: '5a1233bc0f5ae10021650d97',
    name: 'Severus Snape',
    role: 'Professor, Potions',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/severusSnape.jpg'
  },
  {
    _id: '5a1233ff0f5ae10021650d98',
    name: 'Alicia Spinnet',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/aliciaSpinnet.jpg'
  },
  {
    _id: '5a1234500f5ae10021650d99',
    name: 'Pomona Sprout',
    role: 'Professor, Herbology',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/pomonaSprout.jpg'
  },
  {
    _id: '5a1234820f5ae10021650d9a',
    name: 'Pius Thicknesse',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/piusThicknesse.jpg'
  },
  {
    _id: '5a1234cb0f5ae10021650d9b',
    name: 'Dean Thomas',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/deanThomas.jpg'
  },
  {
    _id: '5a1235060f5ae10021650d9c',
    name: 'Andromeda Tonks',
    role: undefined,
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/andromedaTonks.jpg'
  },
  {
    _id: '5a1235790f5ae10021650d9d',
    name: 'Nymphadora Tonks',
    role: 'Auror',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human (metamorphmagus)',
    image: './src/assets/img/nymphadoraTonks.jpg'
  },
  {
    _id: '5a1235c10f5ae10021650d9e',
    name: 'Edward Tonks',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
    image: './src/assets/img/edwardTonks.jpg'
  },
  {
    _id: '5a12361f0f5ae10021650d9f',
    name: 'Travers',
    role: 'Ministry of Magic Official',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/travers.jpg'
  },
  {
    _id: '5a12368a0f5ae10021650da0',
    name: 'Sybill Trelawney',
    role: 'Professor, Divination',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/sybillTrelawney.jpg'
  },
  {
    _id: '5a1236eb0f5ae10021650da1',
    name: 'Dolores Umbridge',
    role: 'Head of the Muggle Born Registration Commission',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
    image: './src/assets/img/doloresUmbridge.jpg'
  },
  {
    _id: '5a1237150f5ae10021650da2',
    name: 'Emmeline Vance',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/emmelineVance.jpg'
  },
  {
    _id: '5a1237480f5ae10021650da3',
    name: 'Romilda Vane',
    role: undefined,
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/romildaVane.jpg'
  },
  {
    _id: '5a12376d0f5ae10021650da4',
    name: 'Septima Vector',
    role: 'Professor, Arithmancy',
    house: undefined,
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/septimaVector.jpg'
  },
  {
    _id: '5a1237c00f5ae10021650da5',
    name: 'Arthur Weasley',
    role: 'Head, Misuse of Muggle Artifacts ',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/arthurWeasley.jpg'
  },
  {
    _id: '5a1238070f5ae10021650da6',
    name: 'William Weasley',
    role: 'Curse Breaker, Gringotts Bank',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/williamWeasley.jpg'
  },
  {
    _id: '5a1238350f5ae10021650da7',
    name: 'Charles Weasley',
    role: 'Dragonologist',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/charlesWeasley.jpg'
  },
  {
    _id: '5a12387a0f5ae10021650da8',
    name: 'Fred Weasley',
    role: "co-owner of Weasleys' Wizard Wheezes",
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/fredWeasley.jpg'
  },
  {
    _id: '5a1238b20f5ae10021650da9',
    name: 'George Weasley',
    role: "co-owner of Weasleys' Wizard Wheezes",
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/georgeWeasley.jpg'
  },
  {
    _id: '5a1239130f5ae10021650daa',
    name: 'Ginevra Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/ginevraWeasley.jpg'
  },
  {
    _id: '5a12393d0f5ae10021650dab',
    name: 'Molly Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/mollyWeasley.jpg'
  },
  {
    _id: '5a12395f0f5ae10021650dac',
    name: 'Percy Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/percyWeasley.jpg'
  },
  {
    _id: '5a1239c80f5ae10021650dad',
    name: 'Ronald Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/ronaldWeasley.jpg'
  },
  {
    _id: '5a1239f10f5ae10021650dae',
    name: 'Oliver Wood',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/oliverWood.jpg'
  },
  {
    _id: '5a123a110f5ae10021650daf',
    name: 'Kennilworthy Whisp',
    role: 'Author, Quiddich Through The Ages',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/kennilworthyWhisp.jpg'
  },
  {
    _id: '5a123a460f5ae10021650db0',
    name: 'Corban Yaxley',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/corbanYaxley.jpg'
  },
  {
    _id: '5a123a710f5ae10021650db1',
    name: 'Blaise Zabini',
    role: undefined,
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/blaiseZabini.jpg'
  },
  {
    _id: '5a123a950f5ae10021650db2',
    name: 'Aragog',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'acromantula',
    image: './src/assets/img/aragog.jpg'
  },
  {
    _id: '5a123aa70f5ae10021650db3',
    name: 'Bane',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
    image: './src/assets/img/bane.jpg'
  },
  {
    _id: '5a123ac60f5ae10021650db4',
    name: 'Beedle the Bard',
    role: 'Fairytale Author',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/beedlethe.jpg'
  },
  {
    _id: '5a123af40f5ae10021650db5',
    name: 'Bloody Baron',
    role: 'Slytherin House Ghost',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
    image: './src/assets/img/bloodyBaron.jpg'
  },
  {
    _id: '5a123b110f5ae10021650db6',
    name: 'Buckbeak',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'hippogriff',
    image: './src/assets/img/buckbeak.jpg'
  },
  {
    _id: '5a123b450f5ae10021650db7',
    name: 'Cadogan',
    role: 'Gryffindor Tower Door Guard',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
    image: './src/assets/img/cadogan.jpg'
  },
  {
    _id: '5a123bfa0f5ae10021650db8',
    name: 'Crookshanks',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'cat',
    image: './src/assets/img/crookshanks.jpg'
  },
  {
    _id: '5a123c260f5ae10021650db9',
    name: 'Dobby',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
    image: './src/assets/img/dobby.jpg'
  },
  {
    _id: '5a123c710f5ae10021650dba',
    name: 'Errol',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Great Grey Owl',
    image: './src/assets/img/errol.jpg'
  },
  {
    _id: '5a123c8c0f5ae10021650dbb',
    name: 'Fang',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Boarhound',
    image: './src/assets/img/fang.jpg'
  },
  {
    _id: '5a123cb40f5ae10021650dbc',
    name: 'Fat Friar',
    role: 'Hufflepuff House Ghost',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
    image: './src/assets/img/fatFriar.jpg'
  },
  {
    _id: '5a123cd20f5ae10021650dbd',
    name: 'Fridfwulfa',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'giant',
    image: './src/assets/img/fridfwulfa.jpg'
  },
  {
    _id: '5a123cf00f5ae10021650dbe',
    name: 'Fat Lady',
    role: 'Gryffindor Tower Door Guard',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'portrait',
    image: './src/assets/img/fatLady.jpg'
  },
  {
    _id: '5a123d3a0f5ae10021650dbf',
    name: 'Fawkes',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'phoenix',
    image: './src/assets/img/fawkes.jpg'
  },
  {
    _id: '5a123d520f5ae10021650dc0',
    name: 'Firenze',
    role: 'Professor, Divination',
    house: undefined,
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
    image: './src/assets/img/firenze.jpg'
  },
  {
    _id: '5a123d680f5ae10021650dc1',
    name: 'Fluffy',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'three-headed dog',
    image: './src/assets/img/fluffy.jpg'
  },
  {
    _id: '5a123d7c0f5ae10021650dc2',
    name: 'Grawp',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'giant',
    image: './src/assets/img/grawp.jpg'
  },
  {
    _id: '5a123d9b0f5ae10021650dc3',
    name: 'Griphook',
    role: 'Employee, Gringotts Wizarding Bank',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'goblin',
    image: './src/assets/img/griphook.jpg'
  },
  {
    _id: '5a123db20f5ae10021650dc4',
    name: 'Hedwig',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Snowy Owl',
    image: './src/assets/img/hedwig.jpg'
  },
  {
    _id: '5a123dc30f5ae10021650dc5',
    name: 'Hokey',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
    image: './src/assets/img/hokey.jpg'
  },
  {
    _id: '5a123de10f5ae10021650dc6',
    name: 'Kreacher',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
    image: './src/assets/img/kreacher.jpg'
  },
  {
    _id: '5a123df10f5ae10021650dc7',
    name: 'Magorian',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
    image: './src/assets/img/magorian.jpg'
  },
  {
    _id: '5a123e450f5ae10021650dc8',
    name: 'Myrtle Warren',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'ghost',
    image: './src/assets/img/myrtleWarren.jpg'
  },
  {
    _id: '5a123e600f5ae10021650dc9',
    name: 'Mrs. Norris',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'cat',
    image: './src/assets/img/mrs.Norris.jpg'
  },
  {
    _id: '5a123e870f5ae10021650dca',
    name: 'Great Aunt Muriel',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/greatAunt.jpg'
  },
  {
    _id: '5a123e9f0f5ae10021650dcb',
    name: 'Nagini',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'horcrux',
    image: './src/assets/img/nagini.jpg'
  },
  {
    _id: '5a123f130f5ae10021650dcc',
    name: 'Nicholas de Mimsy-Porpington',
    role: 'Gryffindor House Ghost',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
    image: './src/assets/img/nicholasde.jpg'
  },
  {
    _id: '5a123f3b0f5ae10021650dcd',
    name: 'Norbert',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Norwegian Ridgeback',
    image: './src/assets/img/norbert.jpg'
  },
  {
    _id: '5a123f7c0f5ae10021650dce',
    name: 'Peeves',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'poltergeist',
    image: './src/assets/img/peeves.jpg'
  },
  {
    _id: '5a123f970f5ae10021650dcf',
    name: 'Pigwidgeon',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'scops owl',
    image: './src/assets/img/pigwidgeon.jpg'
  },
  {
    _id: '5a123fbf0f5ae10021650dd0',
    name: 'Madam Rosmerta',
    role: 'Owner, The Three Broomsticks',
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
    image: './src/assets/img/madamRosmerta.jpg'
  },
  {
    _id: '5a123fd20f5ae10021650dd1',
    name: 'Ronan',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
    image: './src/assets/img/ronan.jpg'
  },
  {
    _id: '5a123fe30f5ae10021650dd2',
    name: 'Trevor',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'toad',
    image: './src/assets/img/trevor.jpg'
  },
  {
    _id: '5a123fff0f5ae10021650dd3',
    name: 'Winky',
    role: undefined,
    house: undefined,
    school: undefined,
    __v: 0,
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
    image: './src/assets/img/winky.jpg'
  }
]


module.exports = personajes;