personajes = [
    {
      _id: '5a0fa4daae5bc100213c232e',
      name: 'Hannah Abbott',
      role: 'student',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/hannahabbott.jpg'
    },
    {
      _id: '5a0fa54aae5bc100213c232f',
      name: 'Bathsheda Babbling',
      role: 'Professor, Ancient Runes',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/bathshedababbling.jpg'
    },
    {
      _id: '5a0fa5deae5bc100213c2330',
      name: 'Ludo Bagman',
      role: 'Head, Department of Magical Games and Sports',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/ludovicbagman.jpg'
    },
    {
      _id: '5a0fa60aae5bc100213c2331',
      name: 'Bathilda Bagshot',
      role: 'Author, A History Of Magic',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/bathildabagshot.jpg'
    },
    {
      _id: '5a0fa648ae5bc100213c2332',
      name: 'Katie Bell',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/katiebell.jpg'
    },
    {
      _id: '5a0fa67dae5bc100213c2333',
      name: 'Cuthbert Binns',
      role: 'Professor, History of Magic',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'ghost',
      image: 'https://apipotter.000webhostapp.com/images/cuthbertbinns.jpg'
    },
    {
      _id: '5a0fa6bbae5bc100213c2334',
      name: 'Phineas Nigellus Black',
      role: '(Formerly) Headmaster of Hogwarts',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/phineasnigellusblack.jpg'
    },
    {
      _id: '5a0fa772ae5bc100213c2337',
      name: 'Regulus Black',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/regulusblack.jpg'
    },
    {
      _id: '5a0fa7dcae5bc100213c2338',
      name: 'Sirius Black',
      role: undefined,
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/siriusblack.jpg'
    },
    {
      _id: '5a0fa842ae5bc100213c2339',
      name: 'Amelia Bones',
      role: 'Head, Department of Magical Law Enforcement',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/ameliabones.jpg'
    },
    {
      _id: '5a0fa86dae5bc100213c233a',
      name: 'Susan Bones',
      role: 'student',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/susanbones.jpg'
    },
    {
      _id: '5a0fa8a6ae5bc100213c233b',
      name: 'Terry Boot',
      role: 'student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/terryboot.jpg'
    },
    {
      _id: '5a107e1ae0686c0021283b19',
      name: 'Lavender Brown',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/lavenderbrown.jpg'
    },
    {
      _id: '5a107e4ae0686c0021283b1a',
      name: 'Millicent Bulstrode',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/millicentbulstrode.jpg'
    },
    {
      _id: '5a107ee3e0686c0021283b1c',
      name: 'Frank Bryce',
      role: 'Gardener, Riddle Family',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/frankbryce.jpg'
    },
    {
      _id: '5a107ebee0686c0021283b1b',
      name: 'Charity Burbage',
      role: 'Professor, Muggle Studies',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/charityburbage.jpg'
    },
    {
      _id: '5a107f17e0686c0021283b1d',
      name: 'Alecto Carrow',
      role: 'Professor, Muggle Studies',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/alectocarrow.jpg'
    },
    {
      _id: '5a107f60e0686c0021283b1e',
      name: 'Amycus Carrow',
      role: 'Professor, Dark Arts',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/amycuscarrow.jpg'
    },
    {
      _id: '5a107f9be0686c0021283b1f',
      name: 'Reginald Cattermole',
      role: 'Employee, Magical Maintenance Department',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/reginaldcattermole.jpg'
    },
    {
      _id: '5a107fc9e0686c0021283b20',
      name: 'Mary Cattermole',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/marycattermole.jpg'
    },
    {
      _id: '5a107ffee0686c0021283b21',
      name: 'Cho Chang',
      role: 'Student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/chochang.jpg'
    },
    {
      _id: '5a108023e0686c0021283b22',
      name: 'Penelope Clearwater',
      role: 'Student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/penelopeclearwater.jpg'
    },
    {
      _id: '5a108047e0686c0021283b23',
      name: 'Michael Corner',
      role: 'Student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/michaelcorner.jpg'
    },
    {
      _id: '5a1093eb3dc2080021cd8753',
      name: 'Crabbe',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/crabbe.jpg'
    },
    {
      _id: '5a10942a3dc2080021cd8754',
      name: 'Vincent Crabbe',
      role: 'Student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/vincentcrabbe.jpg'
    },
    {
      _id: '5a10944f3dc2080021cd8755',
      name: 'Colin Creevey',
      role: 'Student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'muggle-born',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/colincreevey.jpg'
    },
    {
      _id: '5a10947c3dc2080021cd8756',
      name: 'Dennis Creevey',
      role: 'Student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'muggle-born',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/denniscreevey.jpg'
    },
    {
      _id: '5a1094a53dc2080021cd8757',
      name: 'Dirk Cresswell',
      role: 'Head, Goblin Liason Office',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle-born',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/dirkcresswell.jpg'
    },
    {
      _id: '5a1094dc3dc2080021cd8758',
      name: 'Bartemius Crouch Sr.',
      role: 'Head, Department of International Magical Cooperation',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/bartemiuscrouchsr.jpg'
    },
    {
      _id: '5a1094fa3dc2080021cd8759',
      name: 'Bartemius Crouch Jr.',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/bartemiuscrouchjr.jpg'
    },
    {
      _id: '5a10951a3dc2080021cd875a',
      name: 'John Dawlish',
      role: 'Auror',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/johndawlish.jpg'
    },
    {
      _id: '5a1095693dc2080021cd875b',
      name: 'Fleur Delacour',
      role: 'Student',
      house: undefined,
      school: 'Beauxbatons Academy of Magic',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'quarter-villa',
      species: 'part-human',
      image: 'https://apipotter.000webhostapp.com/images/fleurdelacour.jpg'
    },
    {
      _id: '5a1095873dc2080021cd875c',
      name: 'Gabrielle Delacour',
      role: 'Student',
      house: undefined,
      school: 'Beauxbatons Academy of Magic',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'quarter-villa',
      species: 'part-human',
      image: 'https://apipotter.000webhostapp.com/images/gabrielledelacour.jpg'
    },
    {
      _id: '5a1095af3dc2080021cd875d',
      name: 'Dedalus Diggle',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/dedalusdiggle.jpg'
    },
    {
      _id: '5a1095e53dc2080021cd875e',
      name: 'Amos Diggory',
      role: 'Employee, Department for the Regulation and Control of Magical Creatures',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/amosdiggory.jpg'
    },
    {
      _id: '5a1096253dc2080021cd875f',
      name: 'Cedric Diggory',
      role: 'Student',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/cedricdiggory.jpg'
    },
    {
      _id: '5a10964d3dc2080021cd8760',
      name: 'Elphias Doge',
      role: 'Special Advisor to the Wizengamot',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/elphiasdoge.jpg'
    },
    {
      _id: '5a1096743dc2080021cd8761',
      name: 'Antonin Dolohov',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/antonindolohov.jpg'
    },
    {
      _id: '5a1096b33dc2080021cd8762',
      name: 'Aberforth Dumbledore',
      role: "Owner, Hog's Head Inn",
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/aberforthdumbledore.jpg'
    },
    {
      _id: '5a1097653dc2080021cd8763',
      name: 'Albus Dumbledore',
      role: 'Headmaster, Hogwarts',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/albusdumbledore.jpg'
    },
    {
      _id: '5a10977d3dc2080021cd8764',
      name: 'Ariana Dumbledore',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/arianadumbledore.jpg'
    },
    {
      _id: '5a1097943dc2080021cd8765',
      name: 'Dudley Dursley',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/dudleydursley.jpg'
    },
    {
      _id: '5a1097a23dc2080021cd8766',
      name: 'Marjorie Dursley',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/marjoriedursley.jpg'
    },
    {
      _id: '5a1097aa3dc2080021cd8767',
      name: 'Petunia Dursley',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/petuniadursley.jpg'
    },
    {
      _id: '5a1097b03dc2080021cd8768',
      name: 'Vernon Dursley',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'muggle',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/vernondursley.jpg'
    },
    {
      _id: '5a1097d53dc2080021cd8769',
      name: 'Marietta Edgecombe',
      role: 'student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/mariettaedgecombe.jpg'
    },
    {
      _id: '5a1098093dc2080021cd876a',
      name: 'Everard',
      role: '(former) Headmaster, Hogwarts',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/everard.jpg'
    },
    {
      _id: '5a10982c3dc2080021cd876b',
      name: 'Arabella Figg',
      role: 'Dealer of cross-bread cats and kneazies',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'squib',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/arabellafigg.jpg'
    },
    {
      _id: '5a1098653dc2080021cd876c',
      name: 'Argus Filch',
      role: 'Caretaker, Hogwarts',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'squib',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/argusfilch.jpg'
    },
    {
      _id: '5a1098bd3dc2080021cd876d',
      name: 'Justin Finch-Fletchley',
      role: 'student',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/justinfinch-fletchley.jpg'
    },
    {
      _id: '5a1098fd3dc2080021cd876e',
      name: 'Seamus Finnigan',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/seamusfinnigan.jpg'
    },
    {
      _id: '5a1099353dc2080021cd876f',
      name: 'Marcus Flint',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/marcusflint.jpg'
    },
    {
      _id: '5a10995b3dc2080021cd8770',
      name: 'Nicolas Flamel',
      role: 'Alchemist',
      house: undefined,
      school: 'Beauxbatons Academy of Magic',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/nicolasflamel.jpg'
    },
    {
      _id: '5a1099893dc2080021cd8771',
      name: 'Mundungus Fletcher',
      role: 'Dealer of Wizarding Artifacts',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/mundungusfletcher.jpg'
    },
    {
      _id: '5a1099cf3dc2080021cd8772',
      name: 'Filius Flitwick',
      role: 'Professor, Charms',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'part-goblin',
      image: 'https://apipotter.000webhostapp.com/images/filiusflitwick.jpg'
    },
    {
      _id: '5a1099f93dc2080021cd8773',
      name: 'Cornelius Fudge',
      role: 'Minister of Magic',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/corneliusfudge.jpg'
    },
    {
      _id: '5a109a1a3dc2080021cd8774',
      name: 'Marvolo Gaunt',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/marvologaunt.jpg'
    },
    {
      _id: '5a109a253dc2080021cd8775',
      name: 'Merope Gaunt',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/meropegaunt.jpg'
    },
    {
      _id: '5a109a2c3dc2080021cd8776',
      name: 'Morfin Gaunt',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/morfingaunt.jpg'
    },
    {
      _id: '5a109a553dc2080021cd8777',
      name: 'Anthony Goldstein',
      role: 'student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/anthonygoldstein.jpg'
    },
    {
      _id: '5a109a763dc2080021cd8778',
      name: 'Goyle Sr.',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/goylesr.jpg'
    },
    {
      _id: '5a109aa03dc2080021cd8779',
      name: 'Gregory Goyle',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/gregorygoyle.jpg'
    },
    {
      _id: '5a109af13dc2080021cd877a',
      name: 'Hermione Granger',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'muggle-born',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/hermionegranger.jpg'
    },
    {
      _id: '5a109b693dc2080021cd877b',
      name: 'Mykew Gregorovitch',
      role: 'Wand Maker',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/mykewgregorovitch.jpg'
    },
    {
      _id: '5a109b873dc2080021cd877c',
      name: 'Fenrir Greyback',
      role: undefined,
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'unknown',
      species: 'werewolf',
      image: 'https://apipotter.000webhostapp.com/images/fenrirgreyback.jpg'
    },
    {
      _id: '5a109bb33dc2080021cd877d',
      name: 'Gellert Grindelwald',
      role: undefined,
      house: undefined,
      school: 'Durmstrang Institute',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/gellertgrindelwald.jpg'
    },
    {
      _id: '5a109bde3dc2080021cd877e',
      name: 'Wilhelmina Grubbly-Plank',
      role: 'Professor, Care of Magical Creatures',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/wilhelminagrubbly-plank.jpg'
    },
    {
      _id: '5a109bfc3dc2080021cd877f',
      name: 'Godric Gryffindor',
      role: 'Founder, Hogwarts',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/godricgryffindor.jpg'
    },
    {
      _id: '5a109c3d3dc2080021cd8780',
      name: 'Rubeus Hagrid',
      role: 'Groundkeeper, Professor, Care of Magical Creatures',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'half-giant',
      image: 'https://apipotter.000webhostapp.com/images/rubeushagrid.jpg'
    },
    {
      _id: '5a109c5c3dc2080021cd8781',
      name: 'Rolanda Hooch',
      role: 'Quidditch Referee ',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/rolandahooch.jpg'
    },
    {
      _id: '5a109c813dc2080021cd8782',
      name: 'Mafalda Hopkirk',
      role: 'Assistant, mproper Use of Magic Office',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/mafaldahopkirk.jpg'
    },
    {
      _id: '5a109c993dc2080021cd8783',
      name: 'Helga Hufflepuff',
      role: 'Founder, Hogwarts',
      house: 'Hufflepuff',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/helgahufflepuff.jpg'
    },
    {
      _id: '5a109cb83dc2080021cd8784',
      name: 'Angelina Johnson',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/angelinajohnson.jpg'
    },
    {
      _id: '5a109cd33dc2080021cd8785',
      name: 'Lee Jordan',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/leejordan.jpg'
    },
    {
      _id: '5a109cf73dc2080021cd8786',
      name: 'Bertha Jorkins',
      role: 'Department of Magical Games and Sports Employee',
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/berthajorkins.jpg'
    },
    {
      _id: '5a109d2d3dc2080021cd8787',
      name: 'Igor Karkaroff',
      role: 'Headmaster, Durmstrang',
      house: undefined,
      school: 'Durmstrang Institute',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/igorkarkaroff.jpg'
    },
    {
      _id: '5a109d4a3dc2080021cd8788',
      name: 'Viktor Krum',
      role: 'Bulgarian Quiddich Seeker',
      house: undefined,
      school: 'Durmstrang Institute',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/viktorkrum.jpg'
    },
    {
      _id: '5a109d893dc2080021cd8789',
      name: 'Bellatrix Lestrange',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/bellatrixlestrange.jpg'
    },
    {
      _id: '5a109d9f3dc2080021cd878a',
      name: 'Rabastan Lestrange',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/rabastanlestrange.jpg'
    },
    {
      _id: '5a109dab3dc2080021cd878b',
      name: 'Rodolphus Lestrange',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/rodolphuslestrange.jpg'
    },
    {
      _id: '5a109de83dc2080021cd878c',
      name: 'Gilderoy Lockhart',
      role: 'Professor, Defense Against the Dark Arts',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/gilderoylockhart.jpg'
    },
    {
      _id: '5a109e143dc2080021cd878d',
      name: 'Alice Longbottom',
      role: 'Auror (formerly)',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/alicelongbottom.jpg'
    },
    {
      _id: '5a109e1e3dc2080021cd878e',
      name: 'Frank Longbottom',
      role: 'Auror (formerly)',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/franklongbottom.jpg'
    },
    {
      _id: '5a109e253dc2080021cd878f',
      name: 'Augusta Longbottom',
      role: undefined,
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/augustalongbottom.jpg'
    },
    {
      _id: '5a109e543dc2080021cd8790',
      name: 'Neville Longbottom',
      role: 'student',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/nevillelongbottom.jpg'
    },
    {
      _id: '5a109e943dc2080021cd8791',
      name: 'Luna Lovegood',
      role: 'student',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/lunalovegood.jpg'
    },
    {
      _id: '5a109ebd3dc2080021cd8792',
      name: 'Xenophilius Lovegood',
      role: 'Editor, The Quibbler',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/xenophiliuslovegood.jpg'
    },
    {
      _id: '5a109f053dc2080021cd8793',
      name: 'Remus Lupin',
      role: 'Professor, Defence Against the Dark Arts',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'werewolf',
      image: 'https://apipotter.000webhostapp.com/images/remuslupin.jpg'
    },
    {
      _id: '5a109f433dc2080021cd8794',
      name: 'Walden Macnair',
      role: 'Executioner, Committee of Disposal of Dangerous Creatures',
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/waldenmacnair.jpg'
    },
    {
      _id: '5a109f8b3dc2080021cd8795',
      name: 'Draco Malfoy',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/dracomalfoy.jpg'
    },
    {
      _id: '5a109fa83dc2080021cd8796',
      name: 'Lucius Malfoy',
      role: 'School Governer of Hogwarts',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/luciusmalfoy.jpg'
    },
    {
      _id: '5a109fde3dc2080021cd8797',
      name: 'Narcissa Malfoy',
      role: undefined,
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: true,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/narcissamalfoy.jpg'
    },
    {
      _id: '5a1222c50f5ae10021650d6d',
      name: 'Madam Malkin',
      role: "Shop Owner, Madam Malkin's Robes for All Occasions",
      house: undefined,
      school: undefined,
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/madammalkin.jpg'
    },
    {
      _id: '5a12231d0f5ae10021650d6e',
      name: 'Olympe Maxime',
      role: 'Headmistress, Beauxbatons Academy of Magic',
      house: undefined,
      school: 'Beauxbatons Academy of Magic',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-giant',
      species: 'half-giant',
      image: 'https://apipotter.000webhostapp.com/images/olympemaxime.jpg'
    },
    {
      _id: '5a1223720f5ae10021650d6f',
      name: 'Ernest Macmillan',
      role: 'student',
      house: 'Hufflepuff',
      school: 'Hogwarts Academy of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: true,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/ernestmacmillan.jpg'
    },
    {
      _id: '5a1223ed0f5ae10021650d70',
      name: 'Minerva McGonagall',
      role: 'Professor, Transfiguration',
      house: 'Gryffindor',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/minervamcgonagall.jpg'
    },
    {
      _id: '5a1225210f5ae10021650d71',
      name: 'Alastor Moody',
      role: undefined,
      house: undefined,
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: true,
      orderOfThePhoenix: true,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/alastormoody.jpg'
    },
    {
      _id: '5a1225640f5ae10021650d72',
      name: 'Theodore Nott',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'pure-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/theodorenott.jpg'
    },
    {
      _id: '5a1225a20f5ae10021650d73',
      name: 'Garrick Ollivander',
      role: 'Wandmaker',
      house: 'Ravenclaw',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'half-blood',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/garrickollivander.jpg'
    },
    {
      _id: '5a1225e30f5ae10021650d74',
      name: 'Pansy Parkinson',
      role: 'student',
      house: 'Slytherin',
      school: 'Hogwarts School of Witchcraft and Wizardry',
      __v: 0,
      ministryOfMagic: false,
      orderOfThePhoenix: false,
      dumbledoresArmy: false,
      deathEater: false,
      bloodStatus: 'unknown',
      species: 'human',
      image: 'https://apipotter.000webhostapp.com/images/pansyparkinson.jpg'
    },
    {
        _id: '5a12260f0f5ae10021650d75',
        name: 'Padma Patil',
        role: 'student',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/padmapatil.jpg'
      },
      {
        _id: '5a1226520f5ae10021650d76',
        name: 'Parvati Patil',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/parvatipatil.jpg'
      },
      {
        _id: '5a1226d70f5ae10021650d77',
        name: 'Peter Pettigrew',
        role: undefined,
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/peterpettigrew.jpg'
      },
      {
        _id: '5a12273f0f5ae10021650d78',
        name: 'Antioch Peverell',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/antiochpeverell.jpg'
      },
      {
        _id: '5a12276b0f5ae10021650d79',
        name: 'Cadmus Peverell',
        role: 'Owner of the resurrection stone',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/cadmuspeverell.jpg'
      },
      {
        _id: '5a12279f0f5ae10021650d7a',
        name: 'Ignotus Peverell',
        role: 'Owner of the invisibility cloak',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/ignotuspeverell.jpg'
      },
      {
        _id: '5a1227e10f5ae10021650d7b',
        name: 'Irma Pince',
        role: 'Librarian, Hogwarts',
        house: undefined,
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/irmapince.jpg'
      },
      {
        _id: '5a1228070f5ae10021650d7c',
        name: 'Sturgis Podmore',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/sturgispodmore.jpg'
      },
      {
        _id: '5a1228930f5ae10021650d7d',
        name: 'Poppy Pomfrey',
        role: 'Matron, Hogwarts Hospital Wing',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/poppypomfrey.jpg'
      },
      {
        _id: '5a12292a0f5ae10021650d7e',
        name: 'Harry Potter',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/harrypotter.jpg'
      },
      {
        _id: '5a12298d0f5ae10021650d7f',
        name: 'James Potter I',
        role: undefined,
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/jamespotter1.jpg'
      },
      {
        _id: '5a1229e10f5ae10021650d80',
        name: 'Lily J. Potter',
        role: undefined,
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle-born',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/lilyjpotter.jpg'
      },
      {
        _id: '5a122a0e0f5ae10021650d81',
        name: 'Ernest Prang',
        role: 'Driver of the Knight Bus',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/ernestprang.jpg'
      },
      {
        _id: '5a122a880f5ae10021650d82',
        name: 'Quirinus Quirrell',
        role: 'Professor, Defence Against the Dark Arts',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/quirinusquirrell.jpg'
      },
      {
        _id: '5a122ac40f5ae10021650d83',
        name: 'Helena Ravenclaw',
        role: 'Ravenclaw House Ghost',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'ghost',
        image: 'https://apipotter.000webhostapp.com/images/helenaravenclaw.jpg'
      },
      {
        _id: '5a122aef0f5ae10021650d84',
        name: 'Rowena Ravenclaw',
        role: 'Founder, Hogwarts',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/rowenaravenclaw.jpg'
      },
      {
        _id: '5a122b320f5ae10021650d85',
        name: 'Mary Riddle',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/maryriddle.jpg'
      },
      {
        _id: '5a122b510f5ae10021650d86',
        name: 'Thomas Riddle',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/thomasriddle.jpg'
      },
      {
        _id: '5a122b930f5ae10021650d87',
        name: 'Tom Riddle Sr',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/tomriddlesr.jpg'
      },
      {
        _id: '5a122c200f5ae10021650d88',
        name: 'Tom Riddle',
        role: undefined,
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/tomriddle.jpg'
      },
      {
        _id: '5a122cbe0f5ae10021650d89',
        name: 'Demelza Robins',
        role: undefined,
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/demelzarobins.jpg'
      },
      {
        _id: '5a122cf40f5ae10021650d8a',
        name: 'Augustus Rockwood',
        role: 'Unspeakable',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/augustusrockwood.jpg'
      },
      {
        _id: '5a122ea30f5ae10021650d8b',
        name: 'Albert Runcorn',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/albertruncorn.jpg'
      },
      {
        _id: '5a122ecc0f5ae10021650d8c',
        name: 'Scabior',
        role: 'Snatcher',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/scabior.jpg'
      },
      {
        _id: '5a122f3d0f5ae10021650d8d',
        name: 'Newton Scamander ',
        role: 'Author, Fantastic Beasts and Where to Find Them',
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/newtonscamander.jpg'
      },
      {
        _id: '5a122f750f5ae10021650d8e',
        name: 'Rufus Scrimgeour',
        role: 'Head of Auror Office',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/rufusscrimgeour.jpg'
      },
      {
        _id: '5a122fc60f5ae10021650d8f',
        name: 'Kingsley Shacklebolt',
        role: 'Auror',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/kingsleyshacklebolt.jpg'
      },
      {
        _id: '5a1230070f5ae10021650d90',
        name: 'Stanley Shunpike',
        role: 'Conductor of the Knight Bus',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/stanleyshunpike.jpg'
      },
      {
        _id: '5a1230e90f5ae10021650d91',
        name: 'Aurora Sinistra',
        role: 'Professor, Astronomy',
        house: undefined,
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/aurorasinistra.jpg'
      },
      {
        _id: '5a1231fd0f5ae10021650d92',
        name: 'Rita Skeeter',
        role: 'Gossip Correspondant for the Daily Prophet',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/ritaskeeter.jpg'
      },
      {
        _id: '5a1232600f5ae10021650d93',
        name: 'Horace Slughorn',
        role: 'Professor, Potions',
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/horaceslughorn.jpg'
      },
      {
        _id: '5a12327c0f5ae10021650d94',
        name: 'Salazar Slytherin',
        role: 'Founder, Hogwarts',
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/salazarslytherin.jpg'
      },
      {
        _id: '5a1232b10f5ae10021650d95',
        name: 'Hepzibah Smith',
        role: undefined,
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/hepzibahsmith.jpg'
      },
      {
        _id: '5a12333f0f5ae10021650d96',
        name: 'Zacharias Smith',
        role: 'student',
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/zachariassmith.jpg'
      },
      {
        _id: '5a1233bc0f5ae10021650d97',
        name: 'Severus Snape',
        role: 'Professor, Potions',
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/severussnape.jpg'
      },
      {
        _id: '5a1233ff0f5ae10021650d98',
        name: 'Alicia Spinnet',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/aliciaspinnet.jpg'
      },
      {
        _id: '5a1234500f5ae10021650d99',
        name: 'Pomona Sprout',
        role: 'Professor, Herbology',
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/pomonasprout.jpg'
      },
      {
        _id: '5a1234820f5ae10021650d9a',
        name: 'Pius Thicknesse',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/piusthicknesse.jpg'
      },
      {
        _id: '5a1234cb0f5ae10021650d9b',
        name: 'Dean Thomas',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/deanthomas.jpg'
      },
      {
        _id: '5a1235060f5ae10021650d9c',
        name: 'Andromeda Tonks',
        role: undefined,
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/andromedatonks.jpg'
      },
      {
        _id: '5a1235790f5ae10021650d9d',
        name: 'Nymphadora Tonks',
        role: 'Auror',
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human (metamorphmagus)',
        image: 'https://apipotter.000webhostapp.com/images/nymphadoratonks.jpg'
      },
      {
        _id: '5a1235c10f5ae10021650d9e',
        name: 'Edward Tonks',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle-born',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/edwardtonks.jpg'
      },
      {
        _id: '5a12361f0f5ae10021650d9f',
        name: 'Travers',
        role: 'Ministry of Magic Official',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/travers.jpg'
      },
      {
        _id: '5a12368a0f5ae10021650da0',
        name: 'Sybill Trelawney',
        role: 'Professor, Divination',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/sybilltrelawney.jpg'
      },
      {
        _id: '5a1236eb0f5ae10021650da1',
        name: 'Dolores Umbridge',
        role: 'Head of the Muggle Born Registration Commission',
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'half-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/doloresumbridge.jpg'
      },
      {
        _id: '5a1237150f5ae10021650da2',
        name: 'Emmeline Vance',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/emmelinevance.jpg'
      },
      {
        _id: '5a1237480f5ae10021650da3',
        name: 'Romilda Vane',
        role: undefined,
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/romildavane.jpg'
      },
      {
        _id: '5a12376d0f5ae10021650da4',
        name: 'Septima Vector',
        role: 'Professor, Arithmancy',
        house: undefined,
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/septimavector.jpg'
      },
      {
        _id: '5a1237c00f5ae10021650da5',
        name: 'Arthur Weasley',
        role: 'Head, Misuse of Muggle Artifacts ',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/arthurweasley.jpg'
      },
      {
        _id: '5a1238070f5ae10021650da6',
        name: 'William Weasley',
        role: 'Curse Breaker, Gringotts Bank',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/williamweasley.jpg'
      },
      {
        _id: '5a1238350f5ae10021650da7',
        name: 'Charles Weasley',
        role: 'Dragonologist',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/charlesweasley.jpg'
      },
      {
        _id: '5a12387a0f5ae10021650da8',
        name: 'Fred Weasley',
        role: "co-owner of Weasleys' Wizard Wheezes",
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/fredweasley.jpg'
      },
      {
        _id: '5a1238b20f5ae10021650da9',
        name: 'George Weasley',
        role: "co-owner of Weasleys' Wizard Wheezes",
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/georgeweasley.jpg'
      },
      {
        _id: '5a1239130f5ae10021650daa',
        name: 'Ginevra Weasley',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/ginevraweasley.jpg'
      },
      {
        _id: '5a12393d0f5ae10021650dab',
        name: 'Molly Weasley',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/mollyweasley.jpg'
      },
      {
        _id: '5a12395f0f5ae10021650dac',
        name: 'Percy Weasley',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/percyweasley.jpg'
      },
      {
        _id: '5a1239c80f5ae10021650dad',
        name: 'Ronald Weasley',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/ronweasley.jpg'
      },
      {
        _id: '5a1239f10f5ae10021650dae',
        name: 'Oliver Wood',
        role: 'student',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/oliverwood.jpg'
      },
      {
        _id: '5a123a110f5ae10021650daf',
        name: 'Kennilworthy Whisp',
        role: 'Author, Quiddich Through The Ages',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/kennilworthywhisp.jpg'
      },
      {
        _id: '5a123a460f5ae10021650db0',
        name: 'Corban Yaxley',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/corbanyaxley.jpg'
      },
      {
        _id: '5a123a710f5ae10021650db1',
        name: 'Blaise Zabini',
        role: undefined,
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/blaisezabini.jpg'
      },
      {
        _id: '5a123a950f5ae10021650db2',
        name: 'Aragog',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'acromantula',
        image: 'https://apipotter.000webhostapp.com/images/aragog.jpg'
      },
      {
        _id: '5a123aa70f5ae10021650db3',
        name: 'Bane',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'centaur',
        image: 'https://apipotter.000webhostapp.com/images/bane.jpg'
      },
      {
        _id: '5a123ac60f5ae10021650db4',
        name: 'Beedle the Bard',
        role: 'Fairytale Author',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/beedlethebard.jpg'
      },
      {
        _id: '5a123af40f5ae10021650db5',
        name: 'Bloody Baron',
        role: 'Slytherin House Ghost',
        house: 'Slytherin',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'ghost',
        image: 'https://apipotter.000webhostapp.com/images/bloodybaron.jpg'
      },
      {
        _id: '5a123b110f5ae10021650db6',
        name: 'Buckbeak',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'hippogriff',
        image: 'https://apipotter.000webhostapp.com/images/buckbeak.jpg'
      },
      {
        _id: '5a123b450f5ae10021650db7',
        name: 'Cadogan',
        role: 'Gryffindor Tower Door Guard',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'pure-blood',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/cadogan.jpg'
      },
      {
        _id: '5a123bfa0f5ae10021650db8',
        name: 'Crookshanks',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'cat',
        image: 'https://apipotter.000webhostapp.com/images/crookshanks.jpg'
      },
      {
        _id: '5a123c260f5ae10021650db9',
        name: 'Dobby',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'house-elf',
        image: 'https://apipotter.000webhostapp.com/images/dobby.jpg'
      },
      {
        _id: '5a123c710f5ae10021650dba',
        name: 'Errol',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'Great Grey Owl',
        image: 'https://apipotter.000webhostapp.com/images/errol.jpg'
      },
      {
        _id: '5a123c8c0f5ae10021650dbb',
        name: 'Fang',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'Boarhound',
        image: 'https://apipotter.000webhostapp.com/images/fang.jpg'
      },
      {
        _id: '5a123cb40f5ae10021650dbc',
        name: 'Fat Friar',
        role: 'Hufflepuff House Ghost',
        house: 'Hufflepuff',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'ghost',
        image: 'https://apipotter.000webhostapp.com/images/fatfriar.jpg'
      },
      {
        _id: '5a123cd20f5ae10021650dbd',
        name: 'Fridfwulfa',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'giant',
        image: 'https://apipotter.000webhostapp.com/images/fridfwulfa.jpg'
      },
      {
        _id: '5a123cf00f5ae10021650dbe',
        name: 'Fat Lady',
        role: 'Gryffindor Tower Door Guard',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'portrait',
        image: 'https://apipotter.000webhostapp.com/images/fatlady.jpg'
      },
      {
        _id: '5a123d3a0f5ae10021650dbf',
        name: 'Fawkes',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'phoenix',
        image: 'https://apipotter.000webhostapp.com/images/fawkes.jpg'
      },
      {
        _id: '5a123d520f5ae10021650dc0',
        name: 'Firenze',
        role: 'Professor, Divination',
        house: undefined,
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'centaur',
        image: 'https://apipotter.000webhostapp.com/images/firenze.jpg'
      },
      {
        _id: '5a123d680f5ae10021650dc1',
        name: 'Fluffy',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'three-headed dog',
        image: 'https://apipotter.000webhostapp.com/images/fluffy.jpg'
      },
      {
        _id: '5a123d7c0f5ae10021650dc2',
        name: 'Grawp',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'giant',
        image: 'https://apipotter.000webhostapp.com/images/grawp.jpg'
      },
      {
        _id: '5a123d9b0f5ae10021650dc3',
        name: 'Griphook',
        role: 'Employee, Gringotts Wizarding Bank',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'goblin',
        image: 'https://apipotter.000webhostapp.com/images/griphook.jpg'
      },
      {
        _id: '5a123db20f5ae10021650dc4',
        name: 'Hedwig',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'Snowy Owl',
        image: 'https://apipotter.000webhostapp.com/images/hedwig.jpg'
      },
      {
        _id: '5a123dc30f5ae10021650dc5',
        name: 'Hokey',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'house-elf',
        image: 'https://apipotter.000webhostapp.com/images/hokey.jpg'
      },
      {
        _id: '5a123de10f5ae10021650dc6',
        name: 'Kreacher',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'house-elf',
        image: 'https://apipotter.000webhostapp.com/images/kreacher.jpg'
      },
      {
        _id: '5a123df10f5ae10021650dc7',
        name: 'Magorian',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'centaur',
        image: 'https://apipotter.000webhostapp.com/images/magorian.jpg'
      },
      {
        _id: '5a123e450f5ae10021650dc8',
        name: 'Myrtle Warren',
        role: 'student',
        house: 'Ravenclaw',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'muggle-born',
        species: 'ghost',
        image: 'https://apipotter.000webhostapp.com/images/myrtlewarren.jpg'
      },
      {
        _id: '5a123e600f5ae10021650dc9',
        name: 'Mrs. Norris',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'cat',
        image: 'https://apipotter.000webhostapp.com/images/mrs.norris.jpg'
      },
      {
        _id: '5a123e870f5ae10021650dca',
        name: 'Great Aunt Muriel',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/greatauntmuriel.jpg'
      },
      {
        _id: '5a123e9f0f5ae10021650dcb',
        name: 'Nagini',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'horcrux',
        image: 'https://apipotter.000webhostapp.com/images/nagini.jpg'
      },
      {
        _id: '5a123f130f5ae10021650dcc',
        name: 'Nicholas de Mimsy-Porpington',
        role: 'Gryffindor House Ghost',
        house: 'Gryffindor',
        school: 'Hogwarts School of Witchcraft and Wizardry',
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'ghost',
        image: 'https://apipotter.000webhostapp.com/images/nicholasdemimsyporpington.jpg'
      },
      {
        _id: '5a123f3b0f5ae10021650dcd',
        name: 'Norbert',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'Norwegian Ridgeback',
        image: 'https://apipotter.000webhostapp.com/images/norbert.jpg'
      },
      {
        _id: '5a123f7c0f5ae10021650dce',
        name: 'Peeves',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'poltergeist',
        image: 'https://apipotter.000webhostapp.com/images/peeves.jpg'
      },
      {
        _id: '5a123f970f5ae10021650dcf',
        name: 'Pigwidgeon',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'scops owl',
        image: 'https://apipotter.000webhostapp.com/images/pigwidgeon.jpg'
      },
      {
        _id: '5a123fbf0f5ae10021650dd0',
        name: 'Madam Rosmerta',
        role: 'Owner, The Three Broomsticks',
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'human',
        image: 'https://apipotter.000webhostapp.com/images/madamrosmerta.jpg'
      },
      {
        _id: '5a123fd20f5ae10021650dd1',
        name: 'Ronan',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'centaur',
        image: 'https://apipotter.000webhostapp.com/images/ronan.jpg'
      },
      {
        _id: '5a123fe30f5ae10021650dd2',
        name: 'Trevor',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'toad',
        image: 'https://apipotter.000webhostapp.com/images/trevor.jpg'
      },
      {
        _id: '5a123fff0f5ae10021650dd3',
        name: 'Winky',
        role: undefined,
        house: undefined,
        school: undefined,
        __v: 0,
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
        bloodStatus: 'unknown',
        species: 'house-elf',
        image: 'https://apipotter.000webhostapp.com/images/winky.jpg'
      }
    ]

module.exports = personajes;